Azure:
  auth_methods:
  - cli
  - msi
  - devicecode
  cloud: global
AzureSentinel:
  Workspaces:
QueryDefinitions:
  Custom:
  - ./data
  Default:
  - queries
TIProviders:
  TorExitNodes:
    Primary: true
    Provider: Tor
