FROM continuumio/miniconda3

# "Installing conda packages"
# RUN conda create -n firecon python=3.11
# RUN conda init bash
# RUN conda activate firecon
RUN /opt/conda/bin/conda install jupyter -y --quiet

# installing Msticpy requirements and dependencies
RUN pip install azure-cli openpyxl
RUN pip install --upgrade msticpy[all]

USER $NB_UID